### ISSUE TITLE
Issues Auth

### ISSUE THREAD

**Issue by binhnguyen2501** [naviprotocol/navi-aggregator-sdk#10]
I'm using SDK navi-aggregator-sdk version 1.0.8 and call getRoute() it always 401 request 
<img width="378" alt="image" src="https://github.com/user-attachments/assets/7e74146a-9ce9-40de-a9d4-becfd0d153cd">
<img width="378" alt="image" src="https://github.com/user-attachments/assets/90db8793-c43c-46fc-8c4b-66cc3e552f6b">

how can I use getRoute() function without Auth from your SDK

**Comment by binhnguyen2501** [comment]
please check my issue @ComeOnOliver  @navi-dn  @alexayan

**Comment by ComeOnOliver** [comment]
hey, We have moved all aggregator logic to navi-sdk, ^1.4.0, please kindly check the Doc:
https://naviprotocol.gitbook.io/navi-protocol-developer-docs/navi-aggregator

We will deprecate this navi-aggregator-sdk soon
